# Generated by Django 4.2.5 on 2023-09-30 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='место')),
                ('time', models.DateTimeField(verbose_name='время начала выполнения')),
                ('action', models.TextField(verbose_name='действие')),
                ('is_a_pleasant_habit', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('раз в день', 'раз в день'), ('раз в 2 дня', 'раз в 2 дня'), ('раз в 3 дня', 'раз в 3 дня'), ('раз в 4 дня', 'раз в 4 дня'), ('раз в 5 дней', 'раз в 5 дней'), ('раз в 6 дней', 'раз в 6 дней'), ('раз в 7 дней', 'раз в 7 дней')], default='раз в день', max_length=50, verbose_name='периодичность')),
                ('award', models.CharField(blank=True, max_length=255, null=True, verbose_name='вознаграждение')),
                ('time_to_execute', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='время на выполнение')),
                ('is_published', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
